### ISSUE TITLE
Administration Area

### ISSUE THREAD

**Issue by EpicnessTwo** [lrstanley/links#7]
As briefly discussed over IRC, It'd be a nice idea to have some form of administration area where the site owner is able to moderate the links that have been created as well as manually adding their own with a custom/exact link reference.

```
E.g. https://links.wtf/google -> https://google.com
```

The reason for an area for this is because the current database isn't easy to directly modify so that these can be manually added.

**Comment by lrstanley** [comment]
Think I will end up adding both a cli-flag to import shortened links, as well as a administration UI. Going to mock up some things, and see what I can add.

**Comment by lrstanley** [comment]
Added some cli commands for this in https://github.com/lrstanley/links/commit/396445a81dfbdbecfab9e3a6a246d08927b442aa, to add/delete. `add` supports passing a custom id. Don't think I'm going to add an admin ui, due to the indexing speed limitations of the database. BoltDB is really only good at K:V aspects, and not indexing.
